### PR TITLE
Target netstandard2 net40 net46

### PR DESCRIPTION
**Pull request by igitur**
This PR:

- Removes the obsolete `packages.config` file.
- Change targets to `netstandard2.0`, `net40` and `net46` (in line with ClosedXML)
- Replaces `DynamicLinq.cs` with relevant NuGet packages.

### CODE REVIEW

**Comment by igitur** [comment]
This is work in progress.

**Comment by b0bi79** [comment]
I do not remember where it came from. It was something like a CodeProject.
[Here](https://github.com/Microsoft/referencesource/blob/master/System.Web.Extensions/ui/WebControls/Dynamic.cs) is a very similar code, but different.

**Comment by b0bi79** [comment]
Here is https://github.com/kahanu/System.Linq.Dynamic

**Comment by igitur** [comment]
The `System.Linq.Dynamic.Core` NuGet package supports everything this projects needs except the `.Select` in the `ExpressionParseTest` test. I don't think the `.Select` is necessary and removed it.

**Comment by b0bi79** [comment]
ok

**Comment by igitur** [comment]
Ready for review.

**Comment by igitur** [comment]
> Here is https://github.com/kahanu/System.Linq.Dynamic

I tried that package, but it doesn't support Linq statements in queries. Tests were failing. That's why I asked the question and then switched to https://github.com/StefH/System.Linq.Dynamic.Core

**Pull request merged**
