### PR TITLE
Update to ClosedXML version 0.96; drop ClosedXML.Report.Signed

### LINKED ISSUE #194: Breaking change in ClosedXML v0.96
Hi,

Refer to https://github.com/ClosedXML/ClosedXML/pull/1396

This PR has been merged and is quite a big breaking change.

### PR DESCRIPTION
**Pull request by pallu**
Updated and tested

1. ClosedXML updated to version 0.96
2. ClosedXML.Report now became signed; ClosedXML.Report.Signed has been dropped (see https://github.com/ClosedXML/ClosedXML/pull/1552 and https://github.com/ClosedXML/ClosedXML/issues/1547 for wider context)
3. OpenXML version unified in tests.
4. Version bumbed to 0.2.5.

Closes #194

### CODE REVIEW

**Comment by jahav** [comment]
@Pankraty Would it be fine to do a beta release just merge it and upload a beta release on nuget? I am having my hands full with the core project.

@pallu Could you please try to solve why appveyor failed for Report.Signed? Probably needs to set something in the seappveyor.yml.  ClosedXML deprecated Signed version in https://github.com/ClosedXML/ClosedXML/issues/1547.

**Comment by igitur** [comment]
@Pankraty @jahav Maybe skip 0.96 and make it dependent on 0.97? Since 0.96 to 0.97 was quite a big change.

**Comment by Pankraty** [comment]
@igitur, I was thinking that somebody might want to upgrade `.Report` but could face some issues with ClosedXML 0.97 new functionality. If this is the case, then they would stuck. So I thought, maybe we release `0.3` referencing `0.96` and then ship `0.4` referencing `0.97` shortly after. What do you think?

**Comment by jahav** [comment]
@igitur @Pankraty I think your proposed 0.3->0.96, 0.4->0.97 is a good choice. 
The key issue why users want to migrate is removal of `System.Drawing` (=they can run ClosedXML.Report on linux ect), so there needs to be a version of ClosedXML.Report that depends on 0.97.

Can't wait for semantic versioning, but that is a long way before that.

**Comment by jasonlaw** [comment]
any idea when will this publish? thanks! :)

**Comment by CumpsD** [comment]
Looking for 0.97 support as well

**Comment by blahetal** [comment]
Hi, could you release at least a beta version

**Comment by Pankraty** [comment]
@CumpsD, you can now use version 0.2.6

**Comment by CumpsD** [comment]
Thanks!

**Pull request merged**
