### PR TITLE
Add AppVeyor config. Fill in project info.

### PR DESCRIPTION
**Pull request by Pankraty**
I added the project to AppVeyor CI and updated to project info.

### CODE REVIEW

**Comment by igitur** [comment]
I think the entire `AssemblyInfo.cs` can be moved to elements in the `csproj` file.

**Comment by Pankraty** [comment]
Actually I tries but AppVeyor says

> Patching skipped for the following files: tests\ClosedXML.Report.Tests\ClosedXML.Report.Tests.csproj, tests\TestRunner\TestRunner.csproj. Reason is that presumably they are not .NET Core .csproj files.

**Comment by igitur** [comment]
Your appveyor file must contain either `dotnet_csproj` or `assembly_info` depending on whether you want the `.csproj` or the `AssemblyInfo.cs` file patched with the version numbers. See https://www.appveyor.com/docs/build-configuration/#assemblyinfo-patching

I suggest using the `csproj` file with `dotnet_csproj` in `appveyor.yml`. Then you have to delete the `AssemblyInfo.cs` file completely.

**Comment by igitur** [comment]
I also remember something that AppVeyor won't patch elements that are missing. You must include elements with dummy or empty values if you want them patched.

**Comment by Pankraty** [comment]
> Your appveyor file must contain either dotnet_csproj or assembly_info depending on whether you want the .csproj or the AssemblyInfo.cs file patched with the version numbers.

I had `dotnet_csproj` defined when I got that message. My guess - that's because we target a framework version only, not `netstandard`. But I will try once more.

**Comment by igitur** [comment]
Give me the link to the failed appveyor build please

**Comment by Pankraty** [comment]
@igitur is it OK now?

**Comment by igitur** [comment]
Looks good to me, but it's @b0bi79 's final decision.

**Comment by b0bi79** [comment]
Ok, thanks guys.

**Pull request merged**
